name: Bug Report

title: Title of the issue

description: Report an issue with firefox theme. Make sure to read installation instructions.

labels: ["Bug"]

assignees:
  - datguypiko

body:

- type: markdown
  attributes:
    value: |
      <p align="center">
         <img src="https://github.com/datguypiko/.github/blob/main/images/firefox/fox15.png?raw=true" width="100%" height="100%" />
      </p>

- type: dropdown
  attributes:
    label: System OS
    description: Select operating system you are having issue with. Not tested on MacOS, may still check the issue.
    options:
      - Windows
      - Linux
      - MacOS (Not tested)
      - Other
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Select Firefox Build
    description: |
      Select the branch of firefox you reproduce the issue with. Theme code is based on Stable version.  
      `Stable`  - Full support.  
      `Beta`    - May suggest for a manual fix or not.  
      `Nightly` - May suggest for a manual fix or not.  
      `Dev`     - Not Tested.  
      `ESR`     - Not Tested, Try using older theme files.
    options:
       - label: Firefox Stable
       - label: Firefox Beta
       - label: Firefox Nightly
  validations:
    required: true

- type: input
  attributes:
    label: Firefox Version (Optional)
    placeholder: e.g. v140.0.1
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe Your Issue
    description: Issue / Expected behavior / Add picture/video previews.
    placeholder: Report the issue..
  validations:
    required: true

- type: textarea
  attributes:
    label: Your `Chrome` folder structure
    description: Add picture of your `Chrome` folder to see what `Extra Mods` you have and what file structure you are using.
    placeholder: Copy paste or attach files..
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      > [!NOTE]  
      > ###### Make sure that any 3rd party system modifications you’re using aren’t negatively <br> affecting the Firefox window: like micaForEveryone, DWMBlurGlass, startallback <br> or custom linux themes.
