name: Feature Request

title: Title for the feature

description: Request features for FirefoxBlur theme

labels: ["Enhancement"]

assignees:
  - datguypiko

body:

- type: markdown
  attributes:
    value: |
      <div align="center">
         <img src="https://github.com/datguypiko/.github/blob/main/images/firefox/fox10.png?raw=true" width="940" height="300" />
      </div>

- type: textarea
  attributes:
    label: Request Enhancement
    placeholder: Describe the feature you would like to see implemented!
  validations:
    required: true

- type: textarea
  attributes:
    label: Possible implementation (Opional)
    description: CSS Code field - If you have code to suggest potential method of implementing this feature.
    placeholder: Copy paste CSS code here..
    render: CSS
