name: Feature Request

title: Title for the feature

description: Request features for FirefoxBlur theme

labels: ["Enhancement"]

assignees:
  - datguypiko

body:

- type: markdown
  attributes:
    value: |
      > [!WARNING]
      > ###### Test
      ![Preview](https://github.com/user-attachments/assets/a016c5e7-2b0c-42f6-9cfd-b2607511eee7)

- type: textarea
  attributes:
    label: Request Enhancement
    placeholder: Describe the feature you would like to see implemented!
  validations:
    required: true

- type: textarea
  attributes:
    label: Possible implementation (Opional)
    description: CSS Code field - If you have code to suggest potential method of implementing this feature.
    placeholder: Copy paste CSS code here..
    render: CSS
